spring:
  cloud:
    function:
      definition: resultRecieved
    stream:
      default-binder: rabbit
      default:
        group: harness
      bindings:
        resultRecieved-in-0:
          destination: fibcalc-topic
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  application:
    name: test-harness
server:
  port: 8083
