spring:
  cloud:
    stream:
      default-binder: rabbit
      default:
        group: modern
      bindings:
        fibcalc:
          destination: fibcalc-topic
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  application:
    name: legacy
server:
  port: 8081
